pipeline {
    agent any
    stages {
        stage('Pre') {
            steps {
                bat 'echo %runIT%'
                bat 'echo %proName%'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Run') {
            steps {
                bat 'java -jar %mainclasspath%'
            }
        }
    }
}
