pipeline {
    agent any
    stages {
        stage('Pre') {
            steps {
                sh 'echo $runIT'
                sh 'echo $proName'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Run') {
            steps {
                sh 'java -jar %mainclasspath%'
            }
        }
    }
}
